spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello?serverTimezone=SERVER&useSSL=false&allowPublicKeyRetrieval=true
    username: euler
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  sql:
    init:
#      mode: always
      mode: never
      schema-locations: classpath:/org/springframework/batch/core/schema-mysql.sql